# Generated by Django 4.1.2 on 2022-10-18 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='block_1_image',
            field=models.FilePathField(default=None, null=True, path='/img'),
        ),
        migrations.AddField(
            model_name='project',
            name='block_1_text',
            field=models.TextField(default=None, null=True),
        ),
    ]
