# Generated by Django 4.1.2 on 2022-10-18 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_block_1_image_project_block_1_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='block_2_image',
            field=models.FilePathField(default=None, null=True, path='/img'),
        ),
        migrations.AddField(
            model_name='project',
            name='block_2_text',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='block_3_image',
            field=models.FilePathField(default=None, null=True, path='/img'),
        ),
        migrations.AddField(
            model_name='project',
            name='block_3_text',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='target',
            field=models.TextField(default=None, null=True),
        ),
    ]
